// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iplvbouruyidbvhggsdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwbHZib3VydXlpZGJ2aGdnc2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTgwMDEsImV4cCI6MjA2NjIzNDAwMX0.eFDoICSZ000Vb68b4iH_7HpG_hD6HZrfTyS_EJnMvpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);